[defaults]
branch = "release-2026.30"
input_dir = "Nictiz-testscripts/output"
profile = "ggz"

[profiles.allergy]
info_standards = [
  'STU3\AllergyIntolerance-3-0'
]

[profiles.bglz]
info_standards = [
  'STU3\BgLZ-3-0'
]

[profiles.bgz]
info_standards = [
  'STU3\BgZ-3-0'
]

[profiles.bgzmsz122]
info_standards = [
  'STU3\BgZ-MSZ-1-2-2'
]

[profiles.bgzmsz20]
info_standards = [
  'STU3\BgZ-MSZ-2-0'
]

[profiles.eappointment]
info_standards = [
  'STU3\eAppointment-2-0'
]

[profiles.gz1]
info_standards = [
  'STU3\Geboortezorg-1-0'
]

[profiles.gz2]
info_standards = [
  'STU3\Geboortezorg-2'
]

[profiles.genpract]
info_standards = [
  'STU3\GenPractData-2-0'
]

[profiles.ggz]
info_standards = [
  'STU3\GGZ-2-0'
]

[profiles.images]
info_standards = [
  'STU3\Images-2-0'
]

[profiles.lab]
info_standards = [
  'STU3\LaboratoryResults-2-0'
]

[profiles.pdfa]
info_standards = [
  'STU3\PDFA-3-0'
]

[profiles.vitalsigns]
info_standards = [
  'STU3\SelfMeasurements-2-0'
]

[profiles.vi]
info_standards = [
  'R4\Immunization-2-0'
]

[profiles.pc]
info_standards = [
  'R4\PatientCorrections-1-0'
]

[profiles.MO]
info_standards = [
  'R4\MP9-3-0-0-beta\MO'
]

[profiles.MOMM]
info_standards = [
  'R4\MP9-3-0-0-beta\MedMij'
]

# Not complete because too much, only for regressiontesting
[profiles.all]
info_standards = [
  'STU3\AllergyIntolerance-3-0',
  'STU3\BgLZ-3-0',
  'STU3\BgZ-3-0',
  'STU3\BgZ-MSZ-2-0',
  'STU3\eAppointment-2-0',
  'STU3\Geboortezorg-1-0',
  'STU3\Geboortezorg-2',
  'STU3\GenPractData-2-0',
  'STU3\GGZ-2-0',
  'STU3\Images-2-0',
  'STU3\LaboratoryResults-2-0',
  'STU3\PDFA-3-0',
  'STU3\VitalSigns-2-0',
  'R4\Immunization-2-0',
  'R4\PatientCorrections-1-0'
]
