# pytest.ini
[pytest]
addopts = -n 1 --maxfail=10 --tb=short
log_cli = true
log_cli_level = INFO
markers =
    webapp: tests for the Conformancelab webapp
    bulk: run existing Conformancelab tests in bulk
